config/routes.rb
Rails.application.routes.draw do
  resources :events, except: %i[show]
  resources :event_comments, only: %i[create]
  root "events#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id           :integer          not null, primary key
#  company      :string           not null
#  author       :string           not null
#  title        :string           not null
#  description  :text             not null
#  scheduled_at :datetime         not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Event < ApplicationRecord
  default_scope { order(scheduled_at: :asc, created_at: :desc) }

  has_many :event_comments, dependent: :destroy
  has_one :event_comment, dependent: :destroy
end

app/models/event_comment.rb
# == Schema Information
#
# Table name: event_comments
#
#  id            :integer          not null, primary key
#  event_id      :integer          not null
#  identified_by :string           default("Anonymous"), not null
#  comment       :text             not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class EventComment < ApplicationRecord
  default_scope { order(created_at: :desc) }
  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/event_comments_controller.rb
class EventCommentsController < ApplicationController

  def create
    event_comment = EventComment.create(event_comment_params)
    redirect_to edit_event_path(event_comment.event_id)
  end

  private

    def event_comment_params
      params.require(:event_comment).permit(
        :event_id,
        :identified_by,
        :comment
      )
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_events
  before_action :set_event, :only_if_exists, only: [:edit, :update, :destroy]

  def index
  end

  def new
    @event = Event.new
  end

  def create
    Event.create(event_params)
    redirect_to events_path
  end

  def edit
  end

  def update
    @event.update(event_params)
    redirect_to events_path
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def only_if_exists
      redirect_to root_path unless @event.present?
    end

    def set_events
      @events = Event.order(scheduled_at: :desc)
    end

    def event_params
      params.require(:event).permit(
        :company,
        :author,
        :title,
        :description,
        :scheduled_at,
        event_comment_attributes: [:identified_by, :comment]
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def event_comment_abbreviation(event_comment)
    if event_comment
      truncate "#{event_comment.identified_by}: #{event_comment.comment}"
    else
      '...'
    end
  end
end

app/views/event_comments/_event_comment.html.erb
<div class="card mb-4 bg-light">
  <div class="card-body">
    <h5 class="card-title text-muted">Comments</h5>
    <hr />
    <div class="row">
      <div class="col-md-6">
        <div class="row">
          <div class="col-sm-4">Identified By</div>
          <div class="col-sm-8"><strong><%= event_comment.identified_by.present? ? event_comment.identified_by : '...'  %></strong></div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="row">
          <div class="col-sm-4">Comment</div>
          <div class="col-sm-8"><strong><%= event_comment.comment %></strong></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/event_comments/_form.html.erb
<hr />
<div class="card mt-2 mb-4">
  <div class="card-body">
    <h5 class="card-title text-muted">Create Comment</h5>
    <small>Actually have <%= event.event_comments.count %> comments</small>
    <hr />
    <%= form_for :event_comment, url: event_comments_path do |f| %>
      <%= f.hidden_field :event_id, value: event.id %>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group row">
            <%= f.label :identified_by, class: 'col-sm-4 col-form-label' %>
            <div class="col-sm-8">
              <%= f.text_field :identified_by, class: 'form-control', placeholder: 'anonymous...', value: 'Anonymous', required: true %>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group row">
            <%= f.label :comment, class: 'col-sm-4 col-form-label' %>
            <div class="col-sm-8 h-100">
              <%= f.text_area :comment, class: 'form-control h-100', placeholder: 'comment...', rows: 3, required: true %>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <%= f.submit "Add Comment", class: "btn btn-primary btn-sm" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |f| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group row">
        <%= f.label :company, class: 'col-sm-4 col-form-label' %>
        <div class="col-sm-8">
          <%= f.text_field :company, class: 'form-control', placeholder: 'company...', required: true %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :author, class: 'col-sm-4 col-form-label' %>
        <div class="col-sm-8">
          <%= f.text_field :author, class: 'form-control', placeholder: 'author...', required: true %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :title, class: 'col-sm-4 col-form-label' %>
        <div class="col-sm-8">
          <%= f.text_field :title, class: 'form-control', placeholder: 'title...', required: true %>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group row">
        <%= f.label :scheduled_at, class: 'col-sm-4 col-form-label' %>
        <div class="col-sm-8">
          <%= f.date_select :scheduled_at, {}, { class: 'form-control d-inline', style: 'width: auto' } %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :description, class: 'col-sm-4 col-form-label' %>
        <div class="col-sm-8 h-100">
          <%= f.text_area :description, class: 'form-control h-100', placeholder: 'description...', rows: 3, required: true %>
        </div>
      </div>
    </div>

  </div>


  <div class="btn-group btn-group-sm" role="group" aria-label="Actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
    <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" unless event.new_record? %>
  </div>
<% end %>
<% unless event.new_record? %>
  <%= render partial: "event_comments/form", locals: { event: event } %>
  <% event.event_comments.each do |event_comment| %>
    <%= render partial: "event_comments/event_comment", locals: { event_comment: event_comment } %>
  <% end %>
<% end %>

app/views/events/edit.html.erb
<h4>Edit Event</h4>
<hr />
<%= render 'form', event: @event %>

app/views/events/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Company</th>
      <th scope="col">Author</th>
      <th scope="col">Title</th>
      <th scope="col">Last Comment</th>
      <th scope="col">#</th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
    <tr>
      <td>
        <%= event.company %><br />
        <small><%=time_ago_in_words event.scheduled_at %></small>
      </td>
      <td>
        <%= event.author %>
      </td>
      <td>
        <%= event.title %>
      </td>
      <td>
        (<%= event.event_comments.count %> comments:)  <%= event_comment_abbreviation event.event_comment %>
      </td>
      <td>
        <div class="btn-group btn-group-sm" role="group" aria-label="Actions">
          <%= link_to "Edit", edit_event_path(event), class: "btn btn-secondary" %>
          <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/events/new.html.erb
<h4>New Event</h4>
<hr />
<%= render 'form', event: @event %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CompanyScheduler</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>
  <div class="container h-100">
    <div class="row mt-4 justify-content-center align-items-center">
      <div class="col-12 mb-4">
        <h5>Company Scheduler</h5>
        <div class="btn-group  mt-2" role="group" aria-label="Application Actions">
          <%= link_to "Back to Dashboard", root_path, class:"btn btn-secondary" unless current_page?(root_path) %>
          <%= link_to "Create Event", new_event_path, class:"btn btn-primary" %>
        </div>
      </div>
    </div>
    <%= yield %>
  </div>
</body>
</html>